# backtester.py
import pandas as pd
import numpy as np
from strategy import Strategy
from data_fetcher import DataFetcher
from datetime import datetime, timedelta

class Backtester:
    def __init__(self, fyers_client):
        self.data_fetcher = DataFetcher(fyers_client)
    
    def run_backtest(self, symbol, strategy_name, params, resolution, days, 
                     initial_capital=100000, sl_pct=0.02, tp_pct=0.04):
        """Run backtest on historical data"""
        
        print(f"[BACKTEST] Fetching {days} days of {resolution}m data for {symbol}...")
        df = self.data_fetcher.get_historical_data(symbol, resolution, days=days)
        if df is None or len(df) == 0:
            return None
        
        # Generate signals
        strategy = Strategy(strategy_name, params)
        df = strategy.generate_signals(df)
        
        # Simulate trades
        capital = initial_capital
        peak_capital = initial_capital
        max_drawdown = 0
        position = None
        trades = []
        
        for i in range(1, len(df)):
            row = df.iloc[i]
            
            # --- EXIT LOGIC (Check SL/TP/Signal first) ---
            if position is not None:
                exit_price = None
                exit_reason = ""
                
                # Pessimistic assumption: SL hits before TP if both happen in same candle
                if row["low"] <= position["sl"]:
                    exit_price = position["sl"]
                    exit_reason = "SL Hit"
                elif row["high"] >= position["tp"]:
                    exit_price = position["tp"]
                    exit_reason = "TP Hit"
                elif row["signal"] == -1:
                    exit_price = row["close"]
                    exit_reason = "Sell Signal"
                
                if exit_price:
                    pnl = (exit_price - position["entry_price"]) * position["quantity"]
                    points = exit_price - position["entry_price"] # <-- ADD THIS LINE
                    capital += pnl
                    
                    # Track Max Drawdown
                    if capital > peak_capital:
                        peak_capital = capital
                    dd = (peak_capital - capital) / peak_capital
                    if dd > max_drawdown:
                        max_drawdown = dd
                    
                    trades.append({
                        "entry_date": position["entry_date"].strftime('%Y-%m-%d %H:%M'),
                        "exit_date": df.index[i].strftime('%Y-%m-%d %H:%M'),
                        "symbol": symbol,
                        "entry_price": position["entry_price"],
                        "exit_price": exit_price,
                        "points": round(points, 2),       # <-- ADD THIS LINE
                        "quantity": position["quantity"],
                        "pnl": round(pnl, 2),
                        "reason": exit_reason
                    })
                    position = None
            
            # --- ENTRY LOGIC ---
            if position is None and row["signal"] == 1:
                qty = int((capital * 0.95) / row["close"]) # Use 95% of capital
                if qty > 0:
                    position = {
                        "entry_price": row["close"],
                        "entry_date": df.index[i],
                        "quantity": qty,
                        "sl": row["close"] * (1 - sl_pct),
                        "tp": row["close"] * (1 + tp_pct)
                    }
        
        # --- CALCULATE METRICS ---
        if not trades:
            print("[BACKTEST] No trades were generated by this strategy.")
            return None
            
        trades_df = pd.DataFrame(trades)
        wins = trades_df[trades_df["pnl"] > 0]
        losses = trades_df[trades_df["pnl"] < 0]
        
        total_pnl = trades_df["pnl"].sum()
        total_points = trades_df["points"].sum() 
        win_rate = (len(wins) / len(trades_df)) * 100
        avg_win = wins["pnl"].mean() if len(wins) > 0 else 0
        avg_loss = losses["pnl"].mean() if len(losses) > 0 else 0
        
        # Profit Factor (Gross Profit / Gross Loss)
        gross_profit = wins["pnl"].sum() if len(wins) > 0 else 0
        gross_loss = abs(losses["pnl"].sum()) if len(losses) > 0 else 1
        profit_factor = gross_profit / gross_loss if gross_loss != 0 else float('inf')
        
        results = {
            "symbol": symbol,
            "strategy": strategy_name,
            "total_trades": len(trades_df),
            "winning_trades": len(wins),
            "losing_trades": len(losses),
            "win_rate": round(win_rate, 2),
            "total_points": round(total_points, 2),     # <-- ADD THIS LINE
            "total_pnl": round(total_pnl, 2),
            "final_capital": round(capital, 2),
            "return_pct": round(((capital - initial_capital) / initial_capital) * 100, 2),
            "max_drawdown_pct": round(max_drawdown * 100, 2),
            "profit_factor": round(profit_factor, 2),
            "avg_win": round(avg_win, 2),
            "avg_loss": round(avg_loss, 2),
            "trades_df": trades_df
        }
        
        return results
    
    def run_from_dataframe(self, df, symbol, strategy_name, params, 
                           initial_capital=100000, sl_pct=0.02, tp_pct=0.04):
        """Run backtest using an already fetched dataframe (Saves API calls!)"""
        if df is None or len(df) == 0:
            return None
            
        # Generate signals on a COPY to prevent data corruption between strategies
        strategy = Strategy(strategy_name, params)
        df = strategy.generate_signals(df.copy())
        
        # (Rest of the simulation logic is identical to run_backtest)
        capital = initial_capital
        peak_capital = initial_capital
        max_drawdown = 0
        position = None
        trades = []
        
        for i in range(1, len(df)):
            row = df.iloc[i]
            
            if position is not None:
                exit_price = None
                exit_reason = ""
                
                if row["low"] <= position["sl"]:
                    exit_price = position["sl"]
                    exit_reason = "SL Hit"
                elif row["high"] >= position["tp"]:
                    exit_price = position["tp"]
                    exit_reason = "TP Hit"
                elif row["signal"] == -1:
                    exit_price = row["close"]
                    exit_reason = "Sell Signal"
                
                if exit_price:
                    pnl = (exit_price - position["entry_price"]) * position["quantity"]
                    points = exit_price - position["entry_price"]
                    capital += pnl
                    
                    if capital > peak_capital:
                        peak_capital = capital
                    dd = (peak_capital - capital) / peak_capital
                    if dd > max_drawdown:
                        max_drawdown = dd
                    
                    trades.append({
                        "entry_date": position["entry_date"].strftime('%Y-%m-%d %H:%M'),
                        "exit_date": df.index[i].strftime('%Y-%m-%d %H:%M'),
                        "symbol": symbol,
                        "entry_price": position["entry_price"],
                        "exit_price": exit_price,
                        "points": round(points, 2),
                        "quantity": position["quantity"],
                        "pnl": round(pnl, 2),
                        "reason": exit_reason
                    })
                    position = None
            
            if position is None and row["signal"] == 1:
                qty = int((capital * 0.95) / row["close"])
                if qty > 0:
                    position = {
                        "entry_price": row["close"],
                        "entry_date": df.index[i],
                        "quantity": qty,
                        "sl": row["close"] * (1 - sl_pct),
                        "tp": row["close"] * (1 + tp_pct)
                    }
        
        if not trades:
            return None
            
        trades_df = pd.DataFrame(trades)
        wins = trades_df[trades_df["pnl"] > 0]
        losses = trades_df[trades_df["pnl"] < 0]
        
        total_pnl = trades_df["pnl"].sum()
        total_points = trades_df["points"].sum()
        win_rate = (len(wins) / len(trades_df)) * 100
        avg_win = wins["pnl"].mean() if len(wins) > 0 else 0
        avg_loss = losses["pnl"].mean() if len(losses) > 0 else 0
        
        gross_profit = wins["pnl"].sum() if len(wins) > 0 else 0
        gross_loss = abs(losses["pnl"].sum()) if len(losses) > 0 else 1
        profit_factor = gross_profit / gross_loss if gross_loss != 0 else float('inf')
        
        return {
            "symbol": symbol,
            "strategy": strategy_name,
            "total_trades": len(trades_df),
            "winning_trades": len(wins),
            "losing_trades": len(losses),
            "win_rate": round(win_rate, 2),
            "total_points": round(total_points, 2),
            "total_pnl": round(total_pnl, 2),
            "final_capital": round(capital, 2),
            "return_pct": round(((capital - initial_capital) / initial_capital) * 100, 2),
            "max_drawdown_pct": round(max_drawdown * 100, 2),
            "profit_factor": round(profit_factor, 2),
            "avg_win": round(avg_win, 2),
            "avg_loss": round(avg_loss, 2),
            "trades_df": trades_df
        }